services:
  postgresql:
    container_name: pot_postgresql
    image: docker.io/postgres:alpine
    restart: always
    command: -c 'max_connections=1024' -c 'shared_buffers=32GB'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 7432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data

  cube_api:
    container_name: pot_cube_api
    restart: always
    image: octanix/cube:dev #docker.io/cubejs/cube:latest
    ports:
      - 4008:4000
      - 15432:15432
      - 8120:8120
      - 4445:4445
    environment:
      CUBEJS_DB_QUERY_TIMEOUT: 60m
      CUBEJS_CONCURRENCY: 128
      CUBEJS_PG_SQL_PORT: 15432
      CUBEJS_ADBC_PORT: 8120
      CUBEJS_SQL_PORT: 4445
      CUBEJS_DB_MAX_POOL: 128
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_PORT: 5432
      CUBEJS_DB_NAME: pot_examples_dev
      CUBEJS_DB_HOST: postgresql
      CUBEJS_DB_USER: postgres
      CUBEJS_DB_PASS: postgres
      CUBEJS_CUBESTORE_HOST: cubestore_router
      CUBEJS_API_SECRET: secret
      CUBEJS_DEV_MODE: true
      DEBUG_LOG: true
      CUBESQL_LOG_LEVEL: debug
      CUBEJS_LOG_LEVEL: debug
      CUBESQL_ARROW_RESULTS_CACHE_ENABLED: true
    volumes:
      - ./:/cube/conf

  cube_refresh_worker_1:
    container_name: pot_cube_refresh_worker_1
    restart: always
    image: octanix/cube:dev #docker.io/cubejs/cube:latest
    environment:
      CUBEJS_DB_QUERY_TIMEOUT: 60m
      CUBEJS_REFRESH_WORKER_CONCURRENCY: 24
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_PORT: 5432
      CUBEJS_DB_NAME: pot_examples_dev
      CUBEJS_DB_HOST: postgresql
      CUBEJS_DB_USER: postgres
      CUBEJS_DB_PASS: postgres
      CUBEJS_CUBESTORE_HOST: cubestore_router
      CUBEJS_API_SECRET: secret
      CUBEJS_REFRESH_WORKER: "TRUE"
    volumes:
      - ./:/cube/conf

  cube_refresh_worker_2:
    container_name: pot_cube_refresh_worker_2
    restart: always
    image: octanix/cube:dev #docker.io/cubejs/cube:latest
    environment:
      CUBEJS_DB_QUERY_TIMEOUT: 60m
      CUBEJS_REFRESH_WORKER_CONCURRENCY: 24
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_PORT: 5432
      CUBEJS_DB_NAME: pot_examples_dev
      CUBEJS_DB_HOST: postgresql
      CUBEJS_DB_USER: postgres
      CUBEJS_DB_PASS: postgres
      CUBEJS_CUBESTORE_HOST: cubestore_router
      CUBEJS_API_SECRET: secret
      CUBEJS_REFRESH_WORKER: "TRUE"
    volumes:
      - ./:/cube/conf

  cube_refresh_worker_3:
    container_name: pot_cube_refresh_worker_3
    restart: always
    image: octanix/cube:dev #docker.io/cubejs/cube:latest
    environment:
      CUBEJS_DB_QUERY_TIMEOUT: 60m
      CUBEJS_REFRESH_WORKER_CONCURRENCY: 24
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_PORT: 5432
      CUBEJS_DB_NAME: pot_examples_dev
      CUBEJS_DB_HOST: postgresql
      CUBEJS_DB_USER: postgres
      CUBEJS_DB_PASS: postgres
      CUBEJS_CUBESTORE_HOST: cubestore_router
      CUBEJS_API_SECRET: secret
      CUBEJS_REFRESH_WORKER: "TRUE"
    volumes:
      - ./:/cube/conf

  cubestore_router:
    container_name: pot_cubestore_router
    restart: always
    image: octanix/cubestore:dev #docker.io/cubejs/cubestore:latest
    ports:
      - 3306:3306
    environment:
      CUBESTORE_LOG_LEVEL: info
      CUBEJS_SQL_USER: "username"
      CUBEJS_SQL_PASSWORD: "password"
      CUBESTORE_WORKERS: cubestore_worker_1:10001,cubestore_worker_2:10002,cubestore_worker_3:10003,cubestore_worker_4:10004,cubestore_worker_5:10005
      CUBESTORE_REMOTE_DIR: /cube/data
      CUBESTORE_META_PORT: 9999
      CUBESTORE_SERVER_NAME: cubestore_router:9999
    volumes:
      - .cubestore:/cube/data

  cubestore_worker_1:
    container_name: pot_cubestore_worker_1
    restart: always
    image: octanix/cubestore:dev #docker.io/cubejs/cubestore:latest
    environment:
      CUBESTORE_WORKERS: cubestore_worker_1:10001,cubestore_worker_2:10002,cubestore_worker_3:10003,cubestore_worker_4:10004,cubestore_worker_5:10005
      CUBESTORE_SERVER_NAME: cubestore_worker_1:10001
      CUBESTORE_WORKER_PORT: 10001
      CUBESTORE_REMOTE_DIR: /cube/data
      CUBESTORE_META_ADDR: cubestore_router:9999
    volumes:
      - .cubestore:/cube/data

  cubestore_worker_2:
    container_name: pot_cubestore_worker_2
    restart: always
    image: octanix/cubestore:dev #docker.io/cubejs/cubestore:latest
    environment:
      CUBESTORE_WORKERS: cubestore_worker_1:10001,cubestore_worker_2:10002,cubestore_worker_3:10003,cubestore_worker_4:10004,cubestore_worker_5:10005
      CUBESTORE_SERVER_NAME: cubestore_worker_2:10002
      CUBESTORE_WORKER_PORT: 10002
      CUBESTORE_REMOTE_DIR: /cube/data
      CUBESTORE_META_ADDR: cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
  cubestore_worker_3:
    container_name: pot_cubestore_worker_3
    restart: always
    image: octanix/cubestore:dev #docker.io/cubejs/cubestore:latest
    environment:
      CUBESTORE_WORKERS: cubestore_worker_1:10001,cubestore_worker_2:10002,cubestore_worker_3:10003,cubestore_worker_4:10004,cubestore_worker_5:10005
      CUBESTORE_SERVER_NAME: cubestore_worker_3:10003
      CUBESTORE_WORKER_PORT: 10003
      CUBESTORE_REMOTE_DIR: /cube/data
      CUBESTORE_META_ADDR: cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
  cubestore_worker_4:
    container_name: pot_cubestore_worker_4
    restart: always
    image: octanix/cubestore:dev #docker.io/cubejs/cubestore:latest
    environment:
      CUBESTORE_WORKERS: cubestore_worker_1:10001,cubestore_worker_2:10002,cubestore_worker_3:10003,cubestore_worker_4:10004,cubestore_worker_5:10005
      CUBESTORE_SERVER_NAME: cubestore_worker_4:10004
      CUBESTORE_WORKER_PORT: 10004
      CUBESTORE_REMOTE_DIR: /cube/data
      CUBESTORE_META_ADDR: cubestore_router:9999
    volumes:
      - .cubestore:/cube/data

  cubestore_worker_5:
    container_name: pot_cubestore_worker_5
    restart: always
    image: octanix/cubestore:dev #docker.io/cubejs/cubestore:latest
    environment:
      CUBESTORE_WORKERS: cubestore_worker_1:10001,cubestore_worker_2:10002,cubestore_worker_3:10003,cubestore_worker_4:10004,cubestore_worker_5:10005
      CUBESTORE_SERVER_NAME: cubestore_worker_5:10005
      CUBESTORE_WORKER_PORT: 10005
      CUBESTORE_REMOTE_DIR: /cube/data
      CUBESTORE_META_ADDR: cubestore_router:9999
    volumes:
      - .cubestore:/cube/data

volumes:
  postgresql:
